layout_spectrum: 0.9922342
color:
  saturation: 0.6410247
  lightness: 0.6578257
  brandStrength: 1
  brandColors:
    - '#17181D'
    - '#CECFCD'
    - '#FFFFFC'
    - '#A3212F'
    - '#FBCF92'
  rhythmicContrast: 0.6498629
typography_spectrum: 1
name: DigiPix
